### PR TITLE
Issue2948 motor drive

### PR DESCRIPTION
**Pull request by khinkelman**
This is for [Issue#2948](https://github.com/lbl-srg/modelica-buildings/issues/2948). This PR is to be internally reviewed by @khinkelman before moving forward with [PR#3385](https://github.com/lbl-srg/modelica-buildings/pull/3385).

@ZhanweiHe I will get comments/revisions back to you this week.

### CODE REVIEW

**Comment by khinkelman** [comment]
@ZhanweiHe, I will continue reviewing this in further detail, but for the meantime here are some changes that are needed:

- [ ] For all models that you changed/created: Please add your name, date, and description of what changes were made to the `revisions` log. This tells LBNL and everyone who uses the models what was changed and when (very helpful for review and tracking changes). 
- [ ] Please scan over the LBNL MBL User Guide [here](https://simulationresearch.lbl.gov/modelica/userGuide/development.html). In particular, please be sure all models follow the [Naming Conventions](https://simulationresearch.lbl.gov/modelica/releases/v8.0.0/help/Buildings_UsersGuide.html#Buildings.UsersGuide.Conventions). When I refer to "all model" - I mean all the new models that are new with branch `issue2948_MotorDrive`. Since Mingzhe started these developments, you can "compare changes" in a PR (but do not push "Create pull request") on GitHub to compare changes -- like [here](https://github.com/lbl-srg/modelica-buildings/compare/master...ZhanweiHe:modelica-buildings:issue2948_MotorDrive)


Beyond those two, I will need to jump into the models myself for further comments (and to help you with revisions) before telling LBNL that they are ready for review. Please let me know if you have any questions!

**Comment by ZhanweiHe** [comment]
@khinkelman, Thank you so much! I will do that this week.

**Comment by khinkelman** [comment]
@ZhanweiHe I am going to merge this so that I can review locally. I will not make any commits so that we don't create conflicts. Please continue addressing the changes above. I'll add additional revision requests as I go.

**Comment by ZhanweiHe** [comment]
@khinkelman No problem ! Thank you for your help !

**Comment by khinkelman** [comment]
@ZhanweiHe thanks again for working on these models! Here I copy Michael's comments, which we discussed. Please address these in your revisions. 
- [ ] Can we validate the models (per Michael's comment [here](https://github.com/lbl-srg/modelica-buildings/pull/3075#discussion_r931665171)). Please check textbooks and electrical modeling/simulation tools for comparison. This applies to the equipment (e.g., `Chiller`, `HeatPump`, and `Pump`) and `InductionMotors`. Ideally, we should include a `Validation` package that shows the results. (One solution: change the `Examples` package in `InductionMotors` to `Validation`. The same could be done for `Thermofluid` if available. `Coupled` can stay the same.)
- [ ] Boolean on/off for equipment (Michael's comment [here](https://github.com/lbl-srg/modelica-buildings/pull/3075#discussion_r931662041)).

**Comment by khinkelman** [comment]
**Example models:**

- [ ] `SquirrelCageDrive` has a sharp spike in `P` (graph below) and produces some warning messages such as `Model error - division by zero: (simMot.omega_r) / (simMot.torSpe.omega_s) = (127.981) / (0)`. 
image
Can you find out what is causing this spike? Can we design the model to protect against non-physical results like this (that are likely due to the numerical formulation)?
- [ ] `Coupled.Examples.Chiller` -- Power is 0. Please revise example to show the chiller when its working.
- [ ] `Coupled.Examples.HeatPump` -- Spike in `P` and `tau` (see below). This may be the same phenomenon as SquirrelCageDrive.
image
- [ ] `Coupled.Pump` -- `Pum.P` initializes from a very high value (~196kW). Steady state `Pum.P=1.55kW`. Please correct initial conditions to be 0 by default. 
- [ ]  `Coupled.Pump` -- the steady state power from `P.Pum` (with electric motor) and `pum.pum.pum.P` (no electric motor) are quite different (~40% difference). Do you know why this is so high? I would expect the steady state power to be the same for both calculation methods.

**Comment by ZhanweiHe** [comment]
@khinkelman Thank you so much for your insights regarding these matters. 
- [x] The reason for the division by zero issue is not clear. I checked the value of `omega_s` at the simulation time 0.513 s is 184.317 rad/s. 
- [x] The power spike seems related to the motor inrush current when the motor start up or speed up. 
- [x] Zero power in `coupled.Examples.Chiller` is due to the controller parameter `reverseActing`. In chiller, the PID control is direct acting, so if the value of `reverseActing` is `false`, the issue is resolved. 
- [x] No ideas for the pump related issues

**Pull request merged**
